server:

  listen: 8089

  workers: 4

  upstreams:
    - id: node1
      url: https://jsonplaceholder.typicode.com

    - id: node2
      url: http://localhost:8002
    
    - id: node3
      url: http://localhost:8003
  
  headers:
    - key: Authorization
      value: 'Bearer $token'

  rules:
    - path: /
      upstreams:
        - node1
        - node2

    - path: /todos
      upstreams:
        - node1